services:
  db:
    image: postgis/postgis:18-3.6
    container_name: walk-db
    environment:
      POSTGRES_DB: walk
      POSTGRES_USER: walk
      POSTGRES_PASSWORD: walk
    ports:
      - "5433:5432" # Close port?
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./data/walk.sql:/docker-entrypoint-initdb.d/init.sql

  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989" # Close port?
    volumes:
      - ./data/map.osm.pbf:/data/map.osm.pbf
      - ./data/graphhopper:/data
      - ./graphhopper/config.yml:/config.yml
    command: ["-c", "/config.yml"]
    environment:
      - JAVA_OPTS=-Xmx1g -Xms1g

  backend:
    build: ./WalkOfInterest-backend
    container_name: walk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - graphhopper