services:
  db:
    image: postgis/postgis:18-3.6
    container_name: walk-db
    environment:
      POSTGRES_DB: walk
      POSTGRES_USER: walk
      POSTGRES_PASSWORD: walk
    ports:
      - "5433:5432" # Close port?
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./data/walk.sql:/docker-entrypoint-initdb.d/init.sql

  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    ports:
      - "8989:8989" # Close port?
    volumes:
      - ./data/graphhopper:/data
      - ./graphhopper/config.yml:/config.yml
    command: ["-c", "/config.yml"]
    environment:
      - JAVA_OPTS=-Xmx1g -Xms1g

  backend:
    build: ./WalkOfInterest-backend
    container_name: walk-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - graphhopper
    environment:
      - DB_URL=jdbc:postgresql://db:5432/walk
      - DB_USERNAME=walk
      - DB_PASSWORD=walk
      - GH_URL=http://graphhopper:8989
      - SHOW_SQL=true
      - JWT_EXPIRATION=900000
      - JWT_REFRESH_EXPIRATION=2592000000
      - JWT_SECRET=9a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b # I hope you are going to use it :)
